GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/61983d6445065622f6c3c34c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": ""
}

###
PUT  http://localhost:3001/api/persons/:61986390c663a8efc7a0fc4e

{
    "name": "",
    "number": ""
}